version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Print first part of CIRCLE_OIDC_TOKEN_V2
          command: |
            TOKEN_NO_SIG=${CIRCLE_OIDC_TOKEN_V2%.*}
            echo $TOKEN_NO_SIG
