version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pretty print parts of CIRCLE_OIDC_TOKEN_V2
          command: |
            echo $CIRCLE_OIDC_TOKEN_V2 | IFS='.' read -ra PARTS
            HEADER=$(echo -n ${PARTS[0]} | base64 --decode | jq .)
            PAYLOAD=$(echo -n ${PARTS[1]} | base64 --decode | jq .)
            echo "Header:"
            echo "$HEADER"
            echo "Payload:"
            echo "$PAYLOAD"
