version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Pretty print parts of CIRCLE_OIDC_TOKEN_V2
          command: |
            TOKEN_NO_SIG=${CIRCLE_OIDC_TOKEN_V2%.*}
            echo $TOKEN_NO_SIG | IFS='.' read -ra PARTS
            HEADER=$(echo -n ${PARTS[0]} | base64 --decode | python -m json.tool)
            PAYLOAD=$(echo -n ${PARTS[1]} | base64 --decode | python -m json.tool)
            echo "Header:"
            echo "$HEADER"
            echo "Payload:"
            echo "$PAYLOAD"
