version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Print first part of CIRCLE_OIDC_TOKEN_V2
          command: |
            IFS='.' read -ra PARTS <<< "$CIRCLE_OIDC_TOKEN_V2"
            echo ${PARTS[0]}.${PARTS[1]}
